version: "3"

services:
  golangblock-service:
    image: badlog/blockgolang
    container_name: blockchain-golang-server
    build:
      context: ./
    volumes:
      - ./src:/usr/app/src
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    restart: on-failure
