version: "3"

services:
  pyblock-service:
    image: badlog/blockpy
    container_name: blockchain-py-server
    build:
      context: ./
    volumes:
      - ./src:/usr/app/src
    ports:
      - 8000:5000
    restart: on-failure
